cv/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.landing, name="landing"),
    path('predict/', views.getPredictions, name='prediction'),
    path('predict-new/', views.getPredictionsNew, name='predictionNew'),
    path('predict-new-with-img-classifier/', views.getPredictionsNewWithImgClassifier, name='predictionNewWithImgClassifier'),
    path('predictionHome/', views.getPredictionsNewWithImgClassifier, name='predictionHome'),
    path('history/', views.BrainScansListView.as_view(), name='history'),
    path('login/', views.login, name="login"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('prognosis/', views.prognosis, name="prognosis"),
    path('segmentation_block/', views.segmentation_block, name="segmentation_block"),
    path('newdoctor/', views.newdoctor, name="newdoctor"),
    path('doctorlogin/', views.doctorlogin, name="doctorlogin"),
    path('doctordashboard/', views.doctordashboard, name="doctordashboard"),
    path('changepassword/', views.changepassword, name="changepassword"),
    path('dchangepassword/', views.dchangepassword, name="dchangepassword"),
    path('doctorlist/', views.doctorlist, name="doctorlist"), 
    path('delete-doctor/<str:username>/', views.delete_doctor, name='delete_doctor'),
    path('contacts/', views.contact_list, name='contact_list'),
]

deployment/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cv.urls')),
    path('', views.index, name='index'),
    path('', include('cv.urls')),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cv/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# class BrainScans(models.Model):
#     name        = models.CharField(max_length=200)
#     image       = models.ImageField(upload_to='images')
#     imageName   = models.CharField(max_length=200, editable=False, null=True, blank=True, unique=True)
#     prediction  = models.FloatField(editable=False, name="prediction", null=True, max_length=5, blank=True)
#     timestamp   = models.DateTimeField(auto_now_add=True)

#     # doctor = models.ForeignKey('NewDoctor', on_delete=models.CASCADE, related_name='brain_scans')

#     def clean(self):
#         """
#         Overriding clean method to perform custom validation
#         """
#         if BrainScans.objects.filter(imageName=self.imageName).exclude(pk=self.pk).exists():
#             raise ValidationError('An image with this filename already exists.')

#     def __str__(self):
#         return self.name
#     class Meta:
#         app_label  = 'cv'

class Contact(models.Model):
	Name        =models.CharField(max_length=200)
	Email       =models.EmailField()
	Message     =models.TextField()
	Subject     =models.TextField()
	"""docstring for Contact"""
	def __str__(self):
		return self.Name
     


class NewDoctor(models.Model):
    username = models.CharField(max_length=200, unique=True)
    fname = models.CharField(max_length=200)
    lname = models.CharField(max_length=200)
    Email = models.EmailField()
    Password = models.TextField()
    Password1 = models.TextField()

    def __str__(self):
        return self.username

class BrainScans(models.Model):

    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')
    imageName = models.CharField(max_length=200, null=True, blank=True)
    prediction = models.FloatField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    # Define the function inside the class
    def get_default_doctor_id():
        doctor = NewDoctor.objects.first()
        if doctor is not None:
            return doctor.id
        else:
            # Create a new doctor if none exists
            new_doctor = NewDoctor.objects.create(
                username='default',
                fname='Default',
                lname='Doctor',
                email='default@hospital.com',
                password='securepassword123'
            )
            return new_doctor.id

    doctor = models.ForeignKey(
        NewDoctor,
        on_delete=models.CASCADE,
        related_name='brain_scans',
        default=get_default_doctor_id  # Reference the function after it's defined
    )

    def clean(self):
        """
        Overriding clean method to perform custom validation
        """
        if BrainScans.objects.filter(imageName=self.imageName).exclude(pk=self.pk).exists():
            raise ValidationError('An image with this filename already exists.')

    def __str__(self):
        return self.name
    class Meta:
        app_label  = 'cv'
    
# Define the function before the BrainScans model
def get_default_doctor_id():
    doctor = NewDoctor.objects.first()
    if doctor is not None:
        return doctor.id
    else:
        # Create a new doctor if none exists
        new_doctor = NewDoctor.objects.create(
            username='default',
            fname='Default',
            lname='Doctor',
            email='default@hospital.com',
            password='securepassword123'
        )
        return new_doctor.id


# class User(AbstractUser):
#     is_doctor = models.BooleanField(default=False)
#     password_changed = models.BooleanField(default=False) 

#     groups = models.ManyToManyField(
#         'auth.Group',
#         verbose_name='groups',
#         blank=True,
#         help_text='The groups this user belongs to.',
#         related_name='custom_user_groups',  # Change here
#     )

#     user_permissions = models.ManyToManyField(
#         'auth.Permission',
#         verbose_name='user permissions',
#         blank=True,
#         help_text='Specific permissions for this user.',
#         related_name='custom_user_permissions',  # Change here
#     )

templates/brain_scan_predict-new-with-MRI-classifier.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
	<!-- CSS only -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<!-- Fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap" rel="stylesheet">

	<style>
		body {
			font-family: 'Play', sans-serif;
			font-weight: 800;
			background: linear-gradient(#e66465, #9198e5);
		}
		#id_name{
			display: block;
			width: 100%;
			padding: .375rem .75rem;
			font-size: 1rem;
			font-weight: 400;
			line-height: 1.5;
			color: #212529;
			background-color: #fff;
			background-clip: padding-box;
			border: 1px solid #ced4da;
			-webkit-appearance: none;
			-moz-appearance: none;
			appearance: none;
			border-radius: .25rem;
			transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
		}
		#id_image{
			display: block;
			width: 100%;
			padding: .375rem .75rem;
			font-size: 1rem;
			font-weight: 400;
			line-height: 1.5;
			color: #212529;
			background-color: #fff;
			background-clip: padding-box;
			border: 1px solid #ced4da;
			-webkit-appearance: none;
			-moz-appearance: none;
			appearance: none;
			border-radius: .25rem;
			transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
		}

		html {
			scroll-behavior: smooth;
		}
		#myImage {
		filter: grayscale(100%);
		}
	</style>

	<title>Brain Tumor Detection</title>
</head>

<body>
	<div class="container-fluid text-light p-5">
		<a href="{% url 'doctordashboard' %}" class="btn btn-light stretched-link">&larr; Dashboard </a>
		<div class="container p-5">
			<h1 class="display-4 font-weight-bold">Brain Tumor Detection</h1>
			<hr class="bg-light border-2 border-top border-light">

			<div class="container overflow-hidden">
				
					<div class="col-6 col-md-auto col-sm-auto">
						<div class="p-3 border ">
							{% if prediction%}
							<p>Upload brain MRI image:</p>
							{% else %}
							<p>Upload an JPG/JPEG image of a brain Tumor Detection and Segmentation:</p>
							{% endif %}
							<form method="post" enctype="multipart/form-data">
								{% csrf_token %}
								<table class="table table-borderless">
									{{ form.as_table }}
									<tr>
										<td></td>
										<td>
										<div class="d-grid gap-2 col-6 mx-auto">
											<button type="submit" class="btn btn-light stretched-link">Upload!</button>
											
										</div>
										
									</tr>
								</table>
							</form>
							
							{% if isNotumor %}
								<h4 style="float: left; color: White; "> <b> No Tumor class has not any prognosis. </b></h4>
							{% else %}
							<a href="{% url 'prognosis' %}" class="btn btn-light stretched-link">Prognosis &rarr;</a>
							{% endif %}
							<!-- <a href="{% url 'segmentation_block' %}" class="btn btn-light stretched-link" style="float: right;">Segmentation &rarr;</a> -->
							{% if isNotumor %}
								<h4 style="float: right; color: Whi te; "> <b>  No Tumor class has not any segmentation.</b></h4>
							{% else %}
								<a href="{% url 'segmentation_block' %}" class="btn btn-light stretched-link" style="float: right;">Segmentation &rarr;</a>
							{% endif %}
						</div>
				
				</div>
				<div class="container overflow-hidden" style="margin-top: 40px;">
					<div class="col-6 col-md-auto col-sm-auto">
						<div class="p-3 border">
							<h5 class="display-5 font-weight-bold">Last submission</h5>
							<hr class="bg-light border-2 border-top border-light">
							{% if last_prediction %}
							<table class="table table-borderless">
								<tbody>
									<tr>
										<td>Submitter</td>
										<td>:</td>
										<td>{{ last_prediction.name }}</td>
									</tr>
									<tr>
										<td>Image Name</td>
										<td>:</td>
										<td>{{ last_prediction.imageName }}</td>
									</tr>
									<tr>
										<td>Prediction</td>
										<td>:</td>
										<td>{{ last_prediction.prediction }} %</td>
									</tr>
									<tr>
										<td>Timestamp</td>
										<td>:</td>
										<td>{{ last_prediction.timestamp }}</td>
									</tr>
									<tr>
										<td>View Image</td>
										<td>:</td>
										<td><a href="../media/{{last_prediction.image}}">View
												image</a></td>
									</tr>
								</tbody>
							</table>
							{% else %}
							No records found!<br><br>
							{% endif %}
							<a href="{% url 'history' %}" class="btn btn-light stretched-link">View full history &rarr;</a>

						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
	{% if isNotMri %}
	<div class="container-fluid bg-danger text-light p-1">
		<div class="container bg-danger p-1">
			<h5 class="display-7 font-weight-bold">Warning! The uploaded image doesn't look like a MRI scan.</h5>
		</div>
	</div>
	{% endif %}

	<!-- {% if prediction %}
	<div class="jumbotron" id="prediction">
		<div class="container">
			<h1 class="display-7 font-weight-light">The TYPE of Brain Tumor is:</h1>
			<h1 class="display-1 font-weight-bold">
				<bold>{{ prediction }} %</bold>
			</h1>
			<hr class="my-4">
			<center><img src="data:image/jpeg;base64, {{original_image}}" id="image" style="max-width:600px; border-radius: 20%;"></img>
			<br>
			<p>{{imageName}}</p></center>
		</div>
	</div>
	{% endif %} -->



	<!-- 
		code for the predictions of shown in the prediction home
		<h1 class="display-7 font-weight-light">The TYPE of Brain Tumor is:</h1>
				{% if imageName %}
				{% if "Te-gl" in imageName %}
				<h1 class="display-1 font-weight-bold"><bold>Glioma {{ prediction }} %</bold></h1>
				{% elif "Te-me" in imageName %}
				<h1 class="display-1 font-weight-bold"><bold>Meningioma {{ prediction }} %</bold></h1>
				{% elif "Te-no" in imageName %}
				<h1 class="display-1 font-weight-bold"><bold>No Tumor</bold></h1>
				{% elif "Te-pi" in imageName %}
				<h1 class="display-1 font-weight-bold"><bold>Pituitary {{ prediction }} %</bold></h1>
				{% else %}
				<h1 class="display-1 font-weight-bold"><bold>Unknown Type {{ prediction }} %</bold></h1>
				{% endif %}
				{% endif %}
	 -->
		{% if prediction %}
		<div class="jumbotron" id="prediction">
			<div class="container">
				<h1 class="display-7 font-weight-light">The TYPE of Brain Tumor is:</h1>
				{% if imageName %}
				{% if "Te-gl" in imageName %}
				<h1 class="display-1 font-weight-bold"><bold>Glioma </bold></h1>
				{% elif "Te-me" in imageName %}
				<h1 class="display-1 font-weight-bold"><bold>Meningioma</h1>
				{% elif "Te-no" in imageName %}
				<h1 class="display-1 font-weight-bold"><bold>No Tumor</bold></h1>
				{% elif "Te-pi" in imageName %}
				<h1 class="display-1 font-weight-bold"><bold>Pituitary </bold></h1>
				{% else %}
				<h1 class="display-1 font-weight-bold"><bold>Unknown Type  </bold></h1>
				{% endif %}
				{% endif %}
				<hr class="my-4">
				<center><img src="data:image/jpeg;base64, {{original_image}}" id="image" style="max-width:600px; border-radius: 20%;"></img>
				<br>
				<p>{{imageName}}</p></center>
			</div>
		</div>
		{% endif %}

	{% if prediction %}
	<div class="jumbotron" id="prediction">
		<div class="container"> 
			<canvas id="predictionChart"></canvas> 
		</div> 
	</div>
	{% endif %}

	

	


	{% comment %}
	<!-- <form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Upload</button>
	</form> -->
	{% endcomment %}

	

</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
	integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
	crossorigin="anonymous"></script>

<script type="text/javascript">
	function validateFileType() {
		var file = document.getElementById("{{ form.image.id_for_label }}");
		var fileName = file.value;
		var idxDot = fileName.lastIndexOf(".") + 1;
		var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
		if (!(extFile == "jpg" || extFile == "jpeg")) {
			alert("Only jpg/jpeg file is allowed!");
			file.value = '';
		}
	}
</script>
{% if prediction %}
<script>
	window.addEventListener('load', function (event) {
		document.getElementById('prediction').scrollIntoView();
	});
</script>
{% endif %}
</html>

templates/brain_scan_predict-new.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
	<!-- CSS only -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<!-- Fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap" rel="stylesheet">

	<style>
		body {
			font-family: 'Play', sans-serif;
			font-weight: 800;
			
		}
	</style>

	<title>Brain Tumor Detection</title>
</head>

<body>
	
	<div class="container-fluid bg-danger text-light p-1">
		<div class="container bg-danger p-1">
			<!-- <h5 class="display-7 font-weight-bold">This page is deprecated. Use the newer version <a href="{% url 'predictionHome' %}">here</a>.</h5> -->
		</div>
	</div>

	<div class="container-fluid text-light p-5">
		<div class="container p-5">
			<h1 class="display-4 font-weight-bold">Brain Tumor Detection</h1>
			<hr class="bg-light border-2 border-top border-light">

			<div class="container overflow-hidden">
				<div class="row gy-1">
					<div class="col-6 col-md-auto col-sm-auto">
						<div class="p-3 border">
							{% if prediction%}
							<p>Upload brain MRI image:</p>
							{% else %}
							<p>Upload an JPG/JPEG image of a brain MRI to get started:</p>
							{% endif %}
							<form method="post" enctype="multipart/form-data">
								{% csrf_token %}
								<table class="table table-borderless">
									{{ form.as_table }}
									<tr>
										<td></td>
										<td><button type="submit" class="btn btn-primary">Upload!</button></td>
									</tr>
								</table>
							</form>
						</div>
					</div>
					<div class="col-6 col-md-auto col-sm-auto">
						<div class="p-3 border">
							<h5 class="display-5 font-weight-bold">Last submission</h5>
							<hr class="bg-light border-2 border-top border-light">
							{% if last_prediction %}
							<table class="table table-borderless">
								<tbody>
									<tr>
										<td>Submitter</td>
										<td>:</td>
										<td>{{ last_prediction.name }}</td>
									</tr>
									<tr>
										<td>Image Name</td>
										<td>:</td>
										<td>{{ last_prediction.imageName }}</td>
									</tr>
									<tr>
										<td>Prediction</td>
										<td>:</td>
										<td>{{ last_prediction.prediction }} %</td>
									</tr>
									<tr>
										<td>Timestamp</td>
										<td>:</td>
										<td>{{ last_prediction.timestamp }}</td>
									</tr>
									<tr>
										<td>View Image</td>
										<td>:</td>
										<td><a href="../media/{{last_prediction.image}}">View image</a></td>
									</tr>
								</tbody>
							</table>
							{% else %}
							No records found!<br><br>
							{% endif %}
							<a href="../history" class="btn btn-light stretched-link">View full history &rarr;</a>

						</div>
					</div>
				</div>
			</div>

		</div>
	</div>


	{% if prediction %}
	<div class="jumbotron">
		<div class="container">
			<h1 class="display-7 font-weight-light">The likelihood of a brain tumor is:</h1>
			<h1 class="display-1 font-weight-bold">
				<bold>{{ prediction }} %</bold>
			</h1>
			<hr class="my-4">
			<img src="data:image/jpeg;base64, {{original_image}}" style="max-width:600px;"></img>
			<br>
			<p>{{imageName}}</p>
		</div>
	</div>
	{% endif %}
	

	{% comment %}
	<!-- <form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Upload</button>
	</form> -->
	{% endcomment %}


</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
	integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
	crossorigin="anonymous"></script>

<script type="text/javascript">
	function validateFileType() {
		var file = document.getElementById("{{ form.image.id_for_label }}");
		var fileName = file.value;
		var idxDot = fileName.lastIndexOf(".") + 1;
		var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
		if (!(extFile == "jpg" || extFile == "jpeg")) {
			alert("Only jpg/jpeg file is allowed!");
			file.value = '';
		}
	}
</script>

</html>

templates/brain_scan_predict.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
	<!-- CSS only -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<title>Brain Tumor Detection</title>
</head>

<body>

	<div class="container-fluid bg-danger text-light p-1">
		<div class="container bg-danger p-1">
			<h5 class="display-7 font-weight-bold">This page is deprecated. Use the newer version <a href="{% url 'predictionHome' %}">here</a>.</h5>
		</div>
	</div>

	<div class="container-fluid text-light p-5">
		<div class="container p-5">
			<h1 class="display-4 font-weight-bold">Brain Tumor Detection</h1>
			<hr>
			{% if prediction%}
			<p>Upload brain MRI image:</p>
			{% else %}
			<p>Upload an JPG/JPEG image of a brain MRI to get started:</p>
			{% endif %}
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<input type="file" name="{{ form.brain_scan_img.html_name }}"
					id="{{ form.brain_scan_img.id_for_label }}" accept=".jpeg .jpg" required onchange="validateFileType()" />
				<button type="submit" class="btn btn-primary">Upload!</button>
			</form>
		</div>
	</div>

	{% if prediction %}
	<div class="jumbotron">
		<div class="container">
			<h1 class="display-7 font-weight-light">The likelihood of a brain tumor is:</h1>
			<h1 class="display-1 font-weight-bold">
				<bold>{{ prediction }} %</bold>
			</h1>
			<hr class="my-4">
			<img src="data:image/jpeg;base64, {{original_image}}"></img>
			<br>
			<p>{{imageName}}</p>
		</div>
	</div>
	{% endif %}
	

	{% comment %}
	<!-- <form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Upload</button>
	</form> -->
	{% endcomment %}




</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
	integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
	crossorigin="anonymous"></script>

<script type="text/javascript">
    function validateFileType(){
        var file = document.getElementById("{{ form.brain_scan_img.id_for_label }}");
        var fileName = file.value;
        var idxDot = fileName.lastIndexOf(".") + 1;
        var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
        if (!(extFile=="jpg" || extFile=="jpeg")){
            alert("Only jpg/jpeg file is allowed!");
            file.value='';
        }
    }
</script>

</html>